[tool.ruff]
line-length = 88
target-version = "py313"

[tool.ruff.lint]
extend-select = ["I", "F", "E", "W", "UP"]  # isort, flake8, pyupgrade, etc.

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
